### ISSUE TITLE
Add token validation to the fhir proxy

### ISSUE THREAD

**Issue by dancinnamon-okta** [oktadev/okta-smartfhir-demo#13]
Since this implementation is meant to show off the SMART authorization process, I'm currently not worried too much about validating my tokens when i call my APIs (the APIs are public anyway).  Regardless to make this as realistic as possible I should add token validation.

**Comment by sdan22** [comment]
Hi @dancinnamon-okta,

Are you still going to add a lambda authorizer for token validation?

**Comment by dancinnamon-okta** [comment]
Hi @sdan22 - I would like to- I just haven't gotten around to it.  When I do it- I'd like to do more than just a basic authorizer though.  I'd want to put something more comprehensive together that fully handles the expected authorizations that come along with patient/ as well as user/ scopes- and that will require a more sophisticated framework and relational store than I've had time to put together.

**Comment by sdan22** [comment]
@dancinnamon-okta thanks for the update!

I know my next question isn't exactly related to this issue but handling authorizations with patient/ and user/ scope is where I am currently at with FHIR. Do you have any suggestions/recommendations on the approach?

**Comment by dancinnamon-okta** [comment]
I'm closing this out because I have implemented this in: https://github.com/dancinnamon-okta/secured-fhir-proxy
