### ISSUE TITLE
axios certificate issue.

### ISSUE THREAD

**Issue by lquanx** [oktadev/okta-smartfhir-demo#28]
Hi,
In AWS lambda function: okta-smartfhir-auth-demo-dev-smart-authorize-proxy

When axios makes requests to okta server: `https://{{okta.company.com}}/oauth2/v1/clients/{{clientID}}`. I got certificate issue:
```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  config: {
    url: 'https://{{okta.com}}/oauth2/v1/clients/{{clientID}}',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      Authorization: 'SSWS {{token}}',
      'User-Agent': 'axios/0.21.1'
    },
```
The root cause was the certificate of {{okta.company.com}} doesn't contain intermediate certificate. 
As a workaround, I hope there is configuration that let axios ignores certificate issue.

**Comment by dancinnamon-okta** [comment]
Lin- did you resolve this, or were just using a workaround still?  It does look like there is a way to ignore cert errors, but that would be really insecure to totally ignore them.

In the /clients url, are you using the <subdomain.okta.com> hostname, or are you using a custom URL setup within Okta?

**Comment by lquanx** [comment]
We solved the certificate issue. There is no more workaround needed. Thanks for your reply. Indeed, it is insure to ignore certificate errors
