### ISSUE TITLE
Can not get new access token at all, "An invalid audience was specified on the authorize request."

### ISSUE THREAD

**Issue by feroze-shahpurwala-visiontree** [oktadev/okta-smartfhir-demo#60]
Also posted issue here: https://github.com/oktadev/okta-smartfhir-docs/issues/11#issue-1492742284

I have no idea what I am doing wrong. When I try to make a get request to get a patient record I keep getting

"An invalid audience was specified on the authorize request."

<img width="746" alt="image" src="https://user-images.githubusercontent.com/118219830/207151085-fde0bda7-055b-4af4-aa06-f35052571491.png">

I have updated the audience field for the default authorization server and in the requests using postman I make sure the 'aud' and I even tried 'audience' query parameter is added and it is the same as what I put in on the okta website. 

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/118219830/207151366-d731c486-ad14-4b10-98c8-51c4af841242.png">

I have tried so many different settings to get this to work it is basically feeling hopeless. How can I get it to authorize? I keep constantly without fail get the error message 

"An invalid audience was specified on the authorize request."

No matter what I do, I just can not get any different result. I have added the audience changed the audience to different values and made sure it matches the query parameter in the request. 

What else can I do? I am stuck here with this audience error. Please help me.

**Comment by dancinnamon-okta** [comment]
Hi there- sorry you're having issues.... I hope I can help.  First off, I would like to confirm the parameter should be "aud" and not "audience"- I know you mentioned you tried it both ways- but the way that is correct is "aud".

The error you're getting is actually part of the "authorize proxy" that implements some of the SMART-specific aspects of oauth2.  One of those checks is to ensure the aud value is what we expect. 

As shown in the code snippet linked to- the check is against the "EXPECTED_AUD_VALUE" variable within the serverless.yml file.  So it should be that "aud" == "audience from Okta" == "base URL of the project". 

https://github.com/oktadev/okta-smartfhir-demo/blob/2127e87e19ea10c8d755ce8a5be188415b7d9224/lib/authorize.js#L24

I hope that helps!

**Comment by feroze-shahpurwala-visiontree** [comment]
Hey thanks a lot finally I was able to understand and move past that error message! 

Now I am getting: "Unable to validate the redirect_uri passed in”

I am trying to use Postman to make API call to get a patient records and I get this error now. 

Where is the redirect_uri set?

**Comment by feroze-shahpurwala-visiontree** [comment]
￼

In Okta under applications it looks like I have localhost:8080 but since I am using postman, do I change this? What do I change it to here, and then what is the setting to update in postman as well?

**Comment by feroze-shahpurwala-visiontree** [comment]
￼


￼

I updated the redirect uri to be the same postman callback address but it is not working, I set them to be the same in Okta and in postman but it does not work I still get the error

"Unable to validate the redirect_uri passed in.”

**Comment by feroze-shahpurwala-visiontree** [comment]
@dancinnamon-okta  thank you I fixed this by updating the value 'EXPECTED_AUD_VALUE' in serverless.yml and in postman adding the 'aud' query parameter to the authorize url
