### ISSUE TITLE
Try to make a Get Request For Patient but get error "Unable to validate the redirect_uri passed in."

### ISSUE THREAD

**Issue by feroze-shahpurwala-visiontree** [oktadev/okta-smartfhir-demo#61]
Hello, I keep receiving the error: "Unable to validate the redirect_uri passed in."

![image](https://user-images.githubusercontent.com/118219830/207170467-3f74b9be-ceab-4752-a74f-92ecdc2ba1da.png)

![image](https://user-images.githubusercontent.com/118219830/207180537-31720a7d-5182-416f-951f-cd2491e82b42.png)

I updated the redirect uri to be the same postman callback address but it is not working, I set them to be the same in Okta and in postman but it does not work I still get the error

"Unable to validate the redirect_uri passed in.”

What redirect_uri do I use if I am just trying to test from postman? 

In Okta I see a given redirect URI under security identity providers but I am not sure if that is what I should use. What do I update in serverless.yml, and in okta, and in postman to get the redirect URI to work?

**Comment by dancinnamon-okta** [comment]
Ok so in Okta, you need to go into the "applications" menu, and pull up the "application" for your client_id (0oa7jxg1pe9K9BHXw5d7), and within that there will be a config for your redirect_uri there.  You need to have 2 entries in that list within Okta.

The first will be the actual redirect_uri, which in your case will be the https://oauth.pstmn.io/v1/callback that postman uses. 

The second will be your /smart_proxy_callback endpoint- which was deployed along with the other lambdas.  So it's address will be something like: 
https://lddot30aik.execute-api.us-west...../dev/smart_proxy_callback.

With those 2 entries in place, you shouldn't get this error anymore.

**Comment by feroze-shahpurwala-visiontree** [comment]
I just tried this an I get the same error "Unable to validate the redirect_uri passed in." The network request is below with payload and header info

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/118219830/207177483-3e283571-e8ec-4b4e-9e4a-7d18b7eec862.png">

In Okta I have it setup with both the URLs you mention, I added the postman callback and found the smart_proxy_callback url in the service information available after deploying Okta and added that too. See screenshot below with both URL's added. 

<img width="720" alt="image" src="https://user-images.githubusercontent.com/118219830/207177948-50bb2f23-bc06-480f-be02-a1c4032bbecf.png">

As you can see in the request I am passing in the redirect_uri query parameter as 'https://oauth.pstmn.io/v1/callback' the postman redirect_uri.

<img width="650" alt="image" src="https://user-images.githubusercontent.com/118219830/207179530-a50be9ce-51ff-4c83-aaba-54f6841cca76.png">

I tried clearing cookies and overall tried multiple times with this setup and I keep getting the same error message:

"Unable to validate the redirect_uri passed in."

Anything else I should try?

**Comment by dancinnamon-okta** [comment]
Hmm... so that does look like it's configured right.  The /authorize endpoint does make an API call into Okta to actually look at that application config and ensure that your redirect-uri is in that list.  
In order to make that call, it uses the Okta API key in the "API_KEY" serverless.yml variable, and also the "OKTA_ORG" variable to find the Okta tenant to call. I guess I'd wonder if it's not liking one of those.
The OKTA_ORG is just the name of your okta subdomain (so dev-XXXXX.oktapreview.com).

**Comment by feroze-shahpurwala-visiontree** [comment]
The API_KEY I have one defined in serverless.yml but after I deploy it says api keys: none

Could that be the issue? 

<img width="478" alt="image" src="https://user-images.githubusercontent.com/118219830/207983420-f6c1e905-678b-470a-9699-4c4fb3800671.png">

I see that I generate an API Key in Tokens under Security -> API -> Tokens. 

I do that and paste the API key into serverless.yml

**Comment by dancinnamon-okta** [comment]
So the API_KEY that you put into serverless.yml is for making Okta API calls- so the process you described is correct for that.  The "api keys" in that screenshot there is different (it's for an API key for AWS API GW)- so it's OK for it to be blank.

There are a couple of paths you can take at this point.

1- There are pretty extensive cloudwatch logs that get generated, so if you go into cloudwatch, you can search for "okta-smartfhir-auth-demo" and you should see a bunch of logs come up, and hopefully those will give you a better indication as to what it doesn't like.

2- There is an environment variable that I put in the code that totally skips this redirect_uri check- you'd put this around line 44 in serverless.yml.  Note that this is for demo purposes only- this check is a critical security check.  But it may help you along to validate other parts of the implementation at least.

    #Disable redirect_uri validation.
    DISABLE_REDIRECT_URI_VALIDATION: true

**Comment by feroze-shahpurwala-visiontree** [comment]
@dancinnamon-okta 

```
AUTHZ_ISSUER: https://dev-XXXXXXXX.okta.com/oauth2/default
AUTHZ_SERVER: default
OKTA_ORG:  https://dev-XXXXXXXX.okta.com
```

does this look correct to you? Maybe the Authz_server is that incorrect?

**Comment by dancinnamon-okta** [comment]
Yeah that should be OK, at least for testing purposes. Ideally in the real world you'll create a dedicated authz server for SMART/FHIR, and the "audience" of that authz server is the FHIR server that you're standing up. But that's not causing this at the moment.  Right now your validation is actually failing not here, but when validating the client app (postman in this case). So really the main thing to look at is the client application configured in Okta for Postman, ensuring that the client id configured in postman matches what's in Okta, and that the redirect-url that postman gives you is in the list of redirect-urls in the app in Okta.

**Comment by dancinnamon-okta** [comment]
@feroze-shahpurwala-visiontree  - I'm just checking in on this- is there still an issue here?
I also wanted to call out that I did make a significant PR yesterday that adds an automated deploy script, and in general improves the design of the system- so FYI.

**Comment by feroze-shahpurwala-visiontree** [comment]
@dancinnamon-okta I was able to get it all working correctly! The last piece was understand the fhirUserId vs patientId and your explanation was quite helpful. But yes finally after a few hurdles it was exciting to see it all working. Although there seems to be a lot of manual work needed to do in Okta to setup the default scopes and roles and do the roleMapping to complete the Smart Auth implementation. And also after I got it working I realized the fhir Database has no data. So I have to first create some patient records. But I have to setup the scopes and roles and add the user accounts. Just a lot of basic things to do which will probably be automated at some point? Would be nice to have some sort of testDataKit built in that includes all the different smart users and roles like patient and physician, and those users would be stored in the Okta server   and the roles and scopes would all exists in Okta automatically and connected to resources on the fhirServer. So once the server is up and running. You can test it all out by logging in as a certain patient, or maybe physician, and see the different ways the patient picker can work with different logins. Just be easier to get going with something like that.

But overall this implementation is very exciting stuff, definitely a great way to go to have your own fhirServer with Smart Authentication and I like the serverless design and architecture decisions. Thank you for helping me fix my issues when setting everything up.

**Comment by dancinnamon-okta** [comment]
@feroze-shahpurwala-visiontree I appreciate the feedback! Yes I did recently add a new automated deploy script that totally takes away any of the Okta configuration.  It also has a function in it to create a "sample" user with the appropriate data elements filled out on it.  That being said- it still does assume that you have a FHIR service with at least some data within it- so perhaps another iteration could introduce some sort of test dataset or something- like you said.
